### ISSUE TITLE
Conditional GET requests (304) not workingin Chrome and Firefox

### ISSUE THREAD

**Issue by madskristensen** [aspnet/ResponseCaching#135]
Chrome and Firefox sends `Cache-Control: no-cache` when user hits F5. When the response has either an ETag or Last-Modified header and the browser sends a matching If-None-Match and/or If-Modified-Since request header, then a 304 response would be expected. However, due to the cache-control header also being present it doesn't send a successful 304 response. 

The user doesn't control what headers Chrome and Firefox should send on F5

**Comment by JunTaoLuo** [comment]
In [RFC 7234 section 4.3.2](https://tools.ietf.org/html/rfc7234#section-4.3.2):
> A cache MUST NOT evaluate
   conditional header fields that are only applicable to an origin
   server, **found in a request with semantics that cannot be satisfied
   with a cached response**, or applied to a target resource for which it
   has no stored responses; such preconditions are likely intended for
   some other (inbound) server.

This suggests `no-cache` has precedence over the conditional headers, so I think the cache is behaving according to spec. 

However, this is another reason we should design a server-side controlled cache instead of an HTTP cache. cc @glennc @Tratcher

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2604
