### ISSUE TITLE
Support for IDistributedCache

### ISSUE THREAD

**Issue by mgroves** [aspnet/ResponseCaching#137]
It doesn't appear that `ResponseCache` works with `IDistributedCache` ([see this issue](https://github.com/brantburnett/Couchbase.Extensions/issues/8) over at Couchbase.Extensions. Please correct me if I'm wrong.

Will you be adding support for `IDistributedCache` in the future?

**Comment by Jetski5822** [comment]
Was wondering the same!

**Comment by hampos** [comment]
+1

The constructor should be opened to allow injecting other `IResponseCache` implementations.
@JunTaoLuo Any plans on doing just that?

**Comment by JunTaoLuo** [comment]
No current plans for it yet, it will need to be triaged for a future release. cc @muratg

**Comment by theofanis** [comment]
+1 

@JunTaoLuo Any valid reason why this doesn't depend on an injected `IResponseCache` implementation and go with the `new MemoryResponseCache` when calling the internal constructor? 

If you were set to the `MemoryResponseCache` usage, you could make this optional and initialize to `MemoryResponseCache` when omitted, a good documentation would then steer developers on how to use this correctly.

When you say future release, does this mean wait 6 months? The answer is vital because it may make more sense for us to just fork this and go with our own version until you guys push it.

**Comment by muratg** [comment]
@DamianEdwards @glennc

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2603
